#!/bin/bash

TITLE=$(playerctl -p spotify metadata title)
ARTIST=$(playerctl -p spotify metadata artist)

if [ -z "${TITLE}" ] || [ -z "${ARTIST}" ] || [ "${TITLE}" == "(null)" ] || [ "${ARTIST}" == "(null)" ]; then
    echo
    exit 0
fi

echo ${TITLE} '|' ${ARTIST}
