#!/bin/bash

PLAYER=${1:-'spotify'}

TITLE=$(playerctl -p ${PLAYER} metadata title)
ARTIST=$(playerctl -p ${PLAYER} metadata artist)

if [ -z "${TITLE}" ] || [ -z "${ARTIST}" ] || [ "${TITLE}" == "(null)" ] || [ "${ARTIST}" == "(null)" ]; then
    echo
    exit 0
fi

echo ${TITLE} '|' ${ARTIST}
